"Completed Module 8, Fixed Module 7 Task 2"
js-tasks-ru/jsbasic-20230629_sakuro pull request #13
Opened 2023-08-08 11:07 UTC by Ilya-Sakuro

2023-08-08 11:08 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-09 08:56 UTC, SinimaWath requested changes

2023-08-09 08:56 UTC, SinimaWath commented on 7-module/2-task/index.js
>      document.body.removeChild(this.element);
Может быть такое, что елемента нет в dom, поэтому его надо удалять через прямую ссылку: `this.element.remove()`

2023-08-09 08:56 UTC, SinimaWath commented on 8-module/2-task/index.js
> +  #filterProduct(product) {
У тебя тут судя по тестам есть баг в фильтрации по noNuts

2023-08-09 08:56 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    if (noNuts !== undefined && product.nuts !== noNuts && noNuts === true) {
Можно упростить до: `if (noNuts && product.nuts)`

2023-08-09 08:56 UTC, SinimaWath commented on 8-module/2-task/index.js
> +      result = false;
Если хотябы одно условие true, то можно выходить из функции. Так что здесь стоит написать: `return false`

2023-08-09 08:56 UTC, SinimaWath commented on 8-module/2-task/index.js
> +      result = false;
return false

2023-08-09 08:56 UTC, SinimaWath commented on 8-module/2-task/index.js
> +      result = false;
return false

2023-08-09 08:56 UTC, SinimaWath commented on 8-module/2-task/index.js
> +      result = false;
return false

2023-08-09 08:56 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    return result;
return true

2023-08-09 08:56 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    ) {
Упростить до: `if (vegeterianOnly && !product.vegeterian)`

2023-08-09 08:56 UTC, SinimaWath commented on 8-module/2-task/index.js
> +    ) {
Можно упростить до: `if (category && product.category != this.filters.category)`

2023-08-09 10:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-08-09 16:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-08-09 16:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-09 22:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-08-11 09:22 UTC, SinimaWath approved these changes

2023-08-11 09:23 UTC, merged